// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutoDoors.proto

package grpc.test.office;

public interface InputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office.InputRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string motion = 1;</code>
   */
  java.lang.String getMotion();
  /**
   * <code>string motion = 1;</code>
   */
  com.google.protobuf.ByteString
      getMotionBytes();

  /**
   * <code>int32 distance = 2;</code>
   */
  int getDistance();
}
