// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutoDoors.proto

package grpc.test.office;

public final class OfficeServiceImpl {
  private OfficeServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_InputRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_InputRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_office_OutputReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_office_OutputReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017AutoDoors.proto\022\006office\"0\n\014InputReques" +
      "t\022\016\n\006motion\030\001 \001(\t\022\020\n\010distance\030\002 \001(\005\",\n\013O" +
      "utputReply\022\016\n\006lights\030\001 \001(\t\022\r\n\005doors\030\002 \001(" +
      "\t2G\n\010opendoor\022;\n\014MotionDetect\022\024.office.I" +
      "nputRequest\032\023.office.OutputReply\"\000B\'\n\020gr" +
      "pc.test.officeB\021OfficeServiceImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_office_InputRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_office_InputRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_InputRequest_descriptor,
        new java.lang.String[] { "Motion", "Distance", });
    internal_static_office_OutputReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_office_OutputReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_office_OutputReply_descriptor,
        new java.lang.String[] { "Lights", "Doors", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
