// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutoDoors.proto

package grpc.test.office;

public interface OutputReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:office.OutputReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lights = 1;</code>
   */
  java.lang.String getLights();
  /**
   * <code>string lights = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightsBytes();

  /**
   * <code>string doors = 2;</code>
   */
  java.lang.String getDoors();
  /**
   * <code>string doors = 2;</code>
   */
  com.google.protobuf.ByteString
      getDoorsBytes();
}
