// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutoDoors.proto

package grpc.test.office;

/**
 * <pre>
 * The response message contains control on lights and doors based on the request invoked.
 * </pre>
 *
 * Protobuf type {@code office.OutputReply}
 */
public  final class OutputReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:office.OutputReply)
    OutputReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OutputReply.newBuilder() to construct.
  private OutputReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OutputReply() {
    lights_ = "";
    doors_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OutputReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            lights_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            doors_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.test.office.OfficeServiceImpl.internal_static_office_OutputReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.test.office.OfficeServiceImpl.internal_static_office_OutputReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.test.office.OutputReply.class, grpc.test.office.OutputReply.Builder.class);
  }

  public static final int LIGHTS_FIELD_NUMBER = 1;
  private volatile java.lang.Object lights_;
  /**
   * <code>string lights = 1;</code>
   */
  public java.lang.String getLights() {
    java.lang.Object ref = lights_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lights_ = s;
      return s;
    }
  }
  /**
   * <code>string lights = 1;</code>
   */
  public com.google.protobuf.ByteString
      getLightsBytes() {
    java.lang.Object ref = lights_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lights_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOORS_FIELD_NUMBER = 2;
  private volatile java.lang.Object doors_;
  /**
   * <code>string doors = 2;</code>
   */
  public java.lang.String getDoors() {
    java.lang.Object ref = doors_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      doors_ = s;
      return s;
    }
  }
  /**
   * <code>string doors = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDoorsBytes() {
    java.lang.Object ref = doors_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      doors_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getLightsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lights_);
    }
    if (!getDoorsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, doors_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getLightsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lights_);
    }
    if (!getDoorsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, doors_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.test.office.OutputReply)) {
      return super.equals(obj);
    }
    grpc.test.office.OutputReply other = (grpc.test.office.OutputReply) obj;

    boolean result = true;
    result = result && getLights()
        .equals(other.getLights());
    result = result && getDoors()
        .equals(other.getDoors());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LIGHTS_FIELD_NUMBER;
    hash = (53 * hash) + getLights().hashCode();
    hash = (37 * hash) + DOORS_FIELD_NUMBER;
    hash = (53 * hash) + getDoors().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.test.office.OutputReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.test.office.OutputReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.test.office.OutputReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.test.office.OutputReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.test.office.OutputReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.test.office.OutputReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.test.office.OutputReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.test.office.OutputReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.test.office.OutputReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.test.office.OutputReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.test.office.OutputReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.test.office.OutputReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.test.office.OutputReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message contains control on lights and doors based on the request invoked.
   * </pre>
   *
   * Protobuf type {@code office.OutputReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:office.OutputReply)
      grpc.test.office.OutputReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.test.office.OfficeServiceImpl.internal_static_office_OutputReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.test.office.OfficeServiceImpl.internal_static_office_OutputReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.test.office.OutputReply.class, grpc.test.office.OutputReply.Builder.class);
    }

    // Construct using grpc.test.office.OutputReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      lights_ = "";

      doors_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.test.office.OfficeServiceImpl.internal_static_office_OutputReply_descriptor;
    }

    @java.lang.Override
    public grpc.test.office.OutputReply getDefaultInstanceForType() {
      return grpc.test.office.OutputReply.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.test.office.OutputReply build() {
      grpc.test.office.OutputReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.test.office.OutputReply buildPartial() {
      grpc.test.office.OutputReply result = new grpc.test.office.OutputReply(this);
      result.lights_ = lights_;
      result.doors_ = doors_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.test.office.OutputReply) {
        return mergeFrom((grpc.test.office.OutputReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.test.office.OutputReply other) {
      if (other == grpc.test.office.OutputReply.getDefaultInstance()) return this;
      if (!other.getLights().isEmpty()) {
        lights_ = other.lights_;
        onChanged();
      }
      if (!other.getDoors().isEmpty()) {
        doors_ = other.doors_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.test.office.OutputReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.test.office.OutputReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object lights_ = "";
    /**
     * <code>string lights = 1;</code>
     */
    public java.lang.String getLights() {
      java.lang.Object ref = lights_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lights_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lights = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLightsBytes() {
      java.lang.Object ref = lights_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lights_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lights = 1;</code>
     */
    public Builder setLights(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lights_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lights = 1;</code>
     */
    public Builder clearLights() {
      
      lights_ = getDefaultInstance().getLights();
      onChanged();
      return this;
    }
    /**
     * <code>string lights = 1;</code>
     */
    public Builder setLightsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lights_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object doors_ = "";
    /**
     * <code>string doors = 2;</code>
     */
    public java.lang.String getDoors() {
      java.lang.Object ref = doors_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        doors_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string doors = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDoorsBytes() {
      java.lang.Object ref = doors_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        doors_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string doors = 2;</code>
     */
    public Builder setDoors(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      doors_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string doors = 2;</code>
     */
    public Builder clearDoors() {
      
      doors_ = getDefaultInstance().getDoors();
      onChanged();
      return this;
    }
    /**
     * <code>string doors = 2;</code>
     */
    public Builder setDoorsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      doors_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:office.OutputReply)
  }

  // @@protoc_insertion_point(class_scope:office.OutputReply)
  private static final grpc.test.office.OutputReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.test.office.OutputReply();
  }

  public static grpc.test.office.OutputReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OutputReply>
      PARSER = new com.google.protobuf.AbstractParser<OutputReply>() {
    @java.lang.Override
    public OutputReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OutputReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OutputReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OutputReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.test.office.OutputReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

